apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggydeployment
  labels:
    app: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggypod
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggycontainer
        image: prasad6242/swiggy:${BUILD_NUMBER}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
